name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          yarn install
      - name: Create environment variables
        run: |
          touch .env
          echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
          echo GOOGLE_YOUTUBE_CHANNEL_ID=${{ secrets.GOOGLE_YOUTUBE_CHANNEL_ID }} >> .env
      - name: Build Web App - Lira dos Artistas
        run: |
          yarn build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
